language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
 - cargo test --all --verbose
 - rustup component add rustfmt-preview
 # disable it until the formatting will be
 # consistent between stable, beta and nightly.
 # - cargo fmt -- --check
