[package]
name = "pbr"
version = "0.3.1"
authors = ["Ariel Mashraki <ariel@mashraki.co.il>", "Steven Fackler <sfackler@gmail.com>"]
description = "Console progress bar for Rust"
documentation = "http://a8m.github.io/pb/doc/pbr/index.html"
repository = "https://github.com/a8m/pb"
keywords = ["cli", "progress", "terminal", "pb"]
license = "MIT"

[dependencies]
time = "0.1.35"
libc = "0.2.9"
winapi = "0.2"
kernel32-sys = "0.2"

[dev-dependencies]
rand = "*"
