[package]
name = "pbr"
version = "0.0.1"
authors = ["Ariel Mashraki <ariel@mashraki.co.il>"]
description = "Console progress bar for Rust"
documentation = "https://github.com/a8m/pb"
repository = "https://github.com/a8m/pb"
keywords = ["cli", "progress"]
license = "MIT"

[dependencies]
time = "0.1"
libc = "0.1"
winapi = "0.2"
kernel32-sys = "0.1"
